apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
      - name: prestashop
        image: prestashop/prestashop:latest
        env:
        - name: DB_SERVER
          value: "db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "example"
        ports:
        - containerPort: 80
