services:
  prestashop:
    image: prestashop/prestashop:latest
    environment:
      PS_DEV_MODE: 1
      DB_SERVER: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: prestashop
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - prestashop-data:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: prestashop
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pexample"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    depends_on:
      - prestashop
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  prestashop-data:
  db-data:
  redis-data:

